project:
  type: website
  output-dir: ../docs

filters:
  - auto-dark

website:
  title: "handsontable"
  navbar:
    left:
      - index.qmd
      - getting-started.qmd
      - options.qmd
      - in-shiny.qmd
      - about.qmd
  page-footer: |
    ----
    developed by [Kennedy Mwavu](https://github.com/kennedymwavu)
    ----

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
