project:
  type: website
  output-dir: ../docs

website:
  title: "handsontable"
  navbar:
    left:
      - index.qmd
      - getting-started.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
